"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['window.py', 'login.py', 'info', 'template.md', 'pmcutilities.py']
OPTIONS = {}

setup(
    name="Reeves Lab Admin",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
